# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/VHDL/BRAM_Doc/BRAM_Doc.cache/wt [current_project]
set_property parent.project_path D:/VHDL/BRAM_Doc/BRAM_Doc.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
add_files d:/VHDL/BRAM_Doc/BRAMTest.coe
add_files D:/VHDL/BRAM_Doc/BRAM_Doc.srcs/sources_1/bd/BRAM/BRAM.bd
set_property used_in_implementation false [get_files -all d:/VHDL/BRAM_Doc/BRAM_Doc.srcs/sources_1/bd/BRAM/ip/BRAM_blk_mem_gen_0_0/BRAM_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/VHDL/BRAM_Doc/BRAM_Doc.srcs/sources_1/bd/BRAM/BRAM_ooc.xdc]
set_property is_locked true [get_files D:/VHDL/BRAM_Doc/BRAM_Doc.srcs/sources_1/bd/BRAM/BRAM.bd]

read_vhdl -library xil_defaultlib {
  D:/VHDL/BRAM_Doc/BRAM_Doc.srcs/sources_1/new/Top_db.vhd
  D:/VHDL/BRAM_Doc/BRAM_Doc.srcs/sources_1/new/Top_7s.vhd
  D:/VHDL/BRAM_Doc/BRAM_Doc.srcs/sources_1/new/Index_module.vhd
  D:/VHDL/BRAM_Doc/BRAM_Doc.srcs/sources_1/bd/BRAM/hdl/BRAM_wrapper.vhd
  D:/VHDL/BRAM_Doc/BRAM_Doc.srcs/sources_1/new/Mem_Conf_Top.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/VHDL/BRAM_Doc/BRAM_Doc.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files D:/VHDL/BRAM_Doc/BRAM_Doc.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Mem_Conf_Top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Mem_Conf_Top.dcp

catch { report_utilization -file Mem_Conf_Top_utilization_synth.rpt -pb Mem_Conf_Top_utilization_synth.pb }
